import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import CardSlider from "@/components/CardSlider";

const image=(id:string,w=900)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
const doctors=[["Dr. Sumit Paria","GI & Bariatric Surgery","photo-1612349317150-e413f6a5b16d"],["Dr. Priya Tayal","Consultant Radiologist","photo-1594824476967-48c8b964273f"],["Dr. Varun Rehani","Senior Consultant","photo-1582750433449-648ed127bb54"],["Dr. Abhinav Gupta","Consultant Radiologist","photo-1537368910025-700350fe46c7"]];
const hospitals=[["South Delhi","photo-1586773860418-d37222d8fce3"],["Noida","photo-1538108149393-fbbd81895907"],["Ludhiana","photo-1519494026892-80bbd2d6fd0d"],["West Delhi","photo-1516841273335-e39b37888115"]];
const faqs=["What are the first signs of gallstones?","Can gallstones go away without surgery?","What foods trigger gallbladder pain?","How long is recovery after laparoscopic gallbladder surgery?","Is gallbladder removal safe?","Can I live normally without a gallbladder?","When should gallstone pain be treated as an emergency?"];

export default function GallstonesSpecialityPage(){return <div className="massh-site speciality-detail-page"><SiteHeader/><main>
  <section className="speciality-title-hero"><div className="shell"><p>Laparoscopic & General Surgery</p><h1>Gall Stone (Gallbladder Stone) Treatment in Delhi | Advanced & Specialised Care</h1></div></section>
  <div className="shell speciality-layout"><article className="speciality-article">
    <p className="speciality-breadcrumb"><Link href="/">Home</Link> › Specialities › Laparoscopic & General Surgery › Gallstones</p>
    <section><h2>Safe & Advanced Gallstone Treatment in Delhi | Expert Diagnosis</h2><p>Gallstones are hardened deposits that develop in the gallbladder. They may remain silent or cause repeated upper abdominal pain, nausea, indigestion and serious complications when a stone blocks normal bile flow.</p><p>At MASSH, specialists provide accurate diagnosis and personalised care ranging from observation to advanced laparoscopic gallbladder removal. Our approach focuses on safety, smaller incisions, less discomfort and faster recovery.</p></section>
    <section className="speciality-highlight"><div><h2>Best Consultation for Gall Stone Treatment in Delhi</h2><p>A timely surgical consultation helps determine whether symptoms are caused by gallstones and whether treatment is needed. Our team reviews symptoms, ultrasound findings and overall health before recommending care.</p></div><div className="gallstone-art">◉</div></section>
    <section><h2>What Are Gallstones?</h2><p>The gallbladder stores bile produced by the liver. When cholesterol, pigments or salts become imbalanced, they can crystallise and gradually form stones. Stones range from tiny grains to larger deposits and may occur individually or in groups.</p><h3>Common types</h3><ul><li><b>Cholesterol stones:</b> Usually yellow-green and the most common type.</li><li><b>Pigment stones:</b> Darker stones associated with excess bilirubin.</li></ul></section>
    <section><h2>Causes of Gallstones</h2><p>Gallstones can form when bile contains excess cholesterol or bilirubin, when the gallbladder does not empty completely, or when bile becomes unusually concentrated.</p><ul><li>Being overweight or losing weight very rapidly</li><li>Pregnancy and hormonal changes</li><li>A diet high in refined carbohydrates and unhealthy fats</li><li>Diabetes, liver disease or certain blood disorders</li><li>Family history and increasing age</li></ul></section>
    <section><h2>Common Causes of Gallstones</h2><div className="speciality-icon-grid">{[["◒","Excess Cholesterol"],["●","Excess Bilirubin"],["◐","Poor Emptying"],["↕","Rapid Weight Change"]].map(([icon,title])=><article key={title}><b>{icon}</b><h3>{title}</h3><p>Changes in bile chemistry or gallbladder movement may encourage crystal formation.</p></article>)}</div></section>
    <section><h2>Typical Symptoms of Gallstones</h2><ul className="speciality-checks"><li>Sudden or steadily increasing upper-right abdominal pain</li><li>Pain in the upper-middle abdomen after meals</li><li>Pain moving to the back or right shoulder</li><li>Nausea, vomiting, bloating or indigestion</li><li>Fever, chills or jaundice when complications develop</li></ul></section>
    <section><h2>Gallstone Diagnosis At The MASSH Hospital</h2><p>Diagnosis begins with a medical history and examination. Ultrasound is commonly used because it can identify gallstones and signs of inflammation. Blood tests help assess infection, liver function and pancreatic involvement.</p><div className="speciality-steps">{["Clinical consultation and examination","Ultrasound of the abdomen","Blood and liver-function tests","MRCP or other imaging when required"].map((step,index)=><div key={step}><b>{index+1}</b><span>{step}</span></div>)}</div></section>
    <section><h2>What Will Happen If Gallstones Are Not Treated?</h2><p>Silent gallstones may not need treatment, but symptomatic stones can cause recurring attacks. Persistent blockage can lead to gallbladder inflammation, bile-duct infection, jaundice or pancreatitis.</p><div className="article-table"><div><b>Complication</b><b>What It Means</b></div><div><span>Cholecystitis</span><span>Inflammation and possible infection of the gallbladder.</span></div><div><span>Choledocholithiasis</span><span>A stone blocks the common bile duct.</span></div><div><span>Pancreatitis</span><span>A migrating stone blocks the pancreatic duct.</span></div></div></section>
    <section><h2>Treatment Options for Gallbladder Stone Removal</h2><p>Treatment depends on symptoms, complications and overall health. Symptomatic or complicated stones are generally treated by removing the gallbladder rather than removing individual stones.</p><h3>Laparoscopic Cholecystectomy</h3><p>Several small incisions are used to remove the gallbladder with a camera and fine instruments. Most patients walk the same day and return to routine activities quickly.</p><h3>Advanced 3D Laparoscopy</h3><p>High-definition three-dimensional visualisation improves depth perception and precision during surgery.</p><h3>Open Surgery</h3><p>Open surgery may occasionally be needed in complex cases, severe infection or when minimally invasive surgery is not appropriate.</p></section>
    <section><h2>Gallstone Prevention Tips</h2><ul><li>Maintain a healthy weight and avoid crash diets</li><li>Choose fibre-rich food, vegetables and whole grains</li><li>Limit unhealthy fats and highly refined carbohydrates</li><li>Exercise regularly and manage diabetes appropriately</li><li>Attend medical follow-up if gallstones have been identified</li></ul></section>
    <section><h2>Recovery After Gallbladder Stone Surgery</h2><p>Recovery after laparoscopic surgery is usually straightforward. Patients are encouraged to walk, keep incisions clean, take prescribed medicines and gradually return to normal food and activities.</p><ul><li>Short hospital stay in uncomplicated cases</li><li>Early mobilisation and oral diet</li><li>Smaller scars and reduced postoperative discomfort</li><li>Return to routine work according to clinical advice</li></ul></section>
    <section><h2>Life After Gallbladder Stone Removal</h2><p>The liver continues to produce bile after gallbladder removal, and most people return to a normal diet and lifestyle. Smaller, lighter meals may feel more comfortable during the early recovery period.</p><div className="article-table"><div><b>Recovery Stage</b><b>General Guidance</b></div><div><span>First few days</span><span>Gentle walking, wound care and light meals.</span></div><div><span>First two weeks</span><span>Gradual activity increase and scheduled follow-up.</span></div><div><span>Long term</span><span>Balanced diet, regular exercise and normal daily life.</span></div></div></section>
    <section><h2>Who Should Undergo Gallstone Surgery?</h2><ul><li>Patients with repeated painful gallstone attacks</li><li>Gallbladder inflammation or infection</li><li>Stones in the common bile duct</li><li>Gallstone pancreatitis or obstructive jaundice</li><li>Selected high-risk patients advised by a specialist</li></ul></section>
    <section><h2>Why Choose MASSH for Gallstone Stone Treatment?</h2><ul><li>Experienced laparoscopic surgeons</li><li>Advanced 3D visualisation and modern operating rooms</li><li>Evidence-based surgical and anaesthesia protocols</li><li>Personalised recovery and nutritional guidance</li><li>Integrated emergency, imaging and critical-care support</li></ul></section>
  </article><aside className="speciality-sidebar"><div className="speciality-enquiry"><h2>Enquire Now</h2><p>Talk to our gallstone care team.</p><button data-quick-enquiry>Request a Call Back</button><a href="tel:+917290975999">☎ +91-72909-75999</a></div><nav><h3>On This Page</h3>{["Gallstone Overview","Causes","Symptoms","Diagnosis","Treatment Options","Recovery","Prevention"].map(item=><span key={item}>{item}<b>›</b></span>)}</nav></aside></div>
  <section className="speciality-doctors section"><div className="shell"><div className="section-heading"><h2>Meet Our Doctors</h2></div><CardSlider label="gallstone specialists" className="card-grid">{doctors.map(([name,speciality,photo])=><article className="doctor-card" key={name}><img src={image(photo,500)} alt={name}/><h3>{name}</h3><p>{speciality}</p><button data-quick-enquiry>Book Appointment</button></article>)}</CardSlider></div></section>
  <section className="section speciality-reasons"><div className="shell"><div className="section-heading"><h2>Reasons Not to Delay Gallstone Treatment</h2></div><div className="why-layout"><img src={image("photo-1579684385127-1ef15d508118")} alt="Medical consultation"/><div className="why-list">{["Prevent repeat painful attacks","Reduce risk of infection and jaundice","Avoid emergency surgery","Protect the pancreas and bile ducts"].map(reason=><article key={reason}><b>●</b><div><h3>{reason}</h3><p>Timely specialist assessment supports safer treatment and recovery.</p></div></article>)}</div></div></div></section>
  <section className="section speciality-hospitals"><div className="shell"><div className="section-heading"><h2>Hospitals</h2></div><CardSlider label="MASSH hospitals" className="card-grid">{hospitals.map(([name,photo])=><article className="hospital-card" key={name}><img src={image(photo)} alt=""/><h3>{name}</h3><a href="tel:+917290975999">Call Now</a></article>)}</CardSlider></div></section>
  <section className="speciality-faq shell"><div className="section-heading"><h2>Frequently Asked Questions</h2></div>{faqs.map(question=><details key={question}><summary>{question}</summary><p>A specialist can assess your symptoms and investigations to provide advice specific to your condition and health.</p></details>)}</section>
  <section className="section"><div className="shell"><div className="section-heading"><h2>Health Blogs</h2></div><div className="related-service-grid"><Link href="/blogs/learn-about-the-crucial-gallbladder-stone-symptoms-in-women"><b>◉</b><span>Gallbladder Stone Symptoms in Women</span><i>→</i></Link><Link href="/blogs/appendix-pain-location"><b>✚</b><span>Appendix Pain: Symptoms and Location</span><i>→</i></Link><Link href="/blogs/fatty-liver-symptoms"><b>●</b><span>Fatty Liver Symptoms You Should Know</span><i>→</i></Link></div></div></section>
  </main><SiteFooter/></div>}
