import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import type { BlogArticle } from "@/data/blogs";
import { blogArticles } from "@/data/blogs";

export default function GenericBlogArticle({article}:{article:BlogArticle}){
  const similar=blogArticles.filter(item=>item.slug!==article.slug&&(item.category===article.category||item.category==="Health Advice")).slice(0,3);
  const signs=["Persistent or increasing discomfort","Symptoms that return frequently","Changes in appetite, digestion or daily energy","Pain accompanied by fever, vomiting or weakness","Symptoms that interfere with normal activity"];
  return <div className="massh-site article-page"><SiteHeader/><main><article className="health-article shell"><header><p className="article-breadcrumb"><Link href="/blogs">Blogs</Link> › {article.category}</p><h1>{article.title}</h1><div className="article-meta"><span>Written by <b>MASSH</b></span><span>▦ {article.date}</span><span>Medically reviewed</span></div></header><div className="article-hero-media article-hero-single"><img src={article.photo} alt={article.title}/></div><div className="article-body"><p>{article.excerpt} Understanding {article.focus} helps patients recognise changes early, make informed decisions and seek the right clinical care.</p><p>This detailed guide explains the common signs, possible causes, evaluation and treatment options. Symptoms can differ from person to person, so medical assessment remains important whenever concerns persist.</p>
    <section><h2>Quick Overview</h2><div className="article-table"><div><b>Topic</b><b>Essential Information</b></div><div><span>What to watch for</span><span>New, persistent or worsening symptoms that affect normal activity.</span></div><div><span>When to consult</span><span>Arrange an assessment when symptoms recur or do not improve.</span></div><div><span>How it is evaluated</span><span>Medical history, physical examination and appropriate investigations.</span></div><div><span>Treatment approach</span><span>Individualised care based on diagnosis, severity and overall health.</span></div></div></section>
    <section><h2>Understanding {article.focus}</h2><p>{article.focus.charAt(0).toUpperCase()+article.focus.slice(1)} can involve several contributing factors. Lifestyle, age, family history, existing medical conditions and individual biology may all influence symptoms and progression.</p><p>Early evaluation helps distinguish temporary discomfort from a condition requiring targeted treatment. A specialist may recommend blood tests, imaging or other investigations depending on the symptoms.</p></section>
    <section><h2>Common Signs and Symptoms</h2><ul className="warning-list">{signs.map(sign=><li key={sign}>{sign}</li>)}</ul><p>Not everyone experiences every symptom. The intensity of a symptom does not always indicate the seriousness of its cause, which is why a professional assessment is valuable.</p></section>
    <section><h2>Diagnosis and Medical Evaluation</h2><p>Your doctor will discuss when symptoms began, what makes them better or worse and whether other health conditions are present. Examination and diagnostic testing are selected according to the likely cause.</p><div className="numbered-copy"><b>1</b><div><h3>Clinical Consultation</h3><p>A detailed history and examination identify important patterns and risk factors.</p></div></div><div className="numbered-copy"><b>2</b><div><h3>Recommended Investigations</h3><p>Blood tests or imaging may be advised to confirm the diagnosis and assess severity.</p></div></div><div className="numbered-copy"><b>3</b><div><h3>Personalised Care Plan</h3><p>The clinical team explains suitable treatment, recovery and follow-up options.</p></div></div></section>
    <section><h2>Treatment and Recovery</h2><p>Treatment depends on the confirmed diagnosis and may include monitoring, lifestyle changes, medication, minimally invasive procedures or surgery. MASSH specialists focus on evidence-based treatment and clear recovery guidance.</p><p>Follow-up is an essential part of care. Attend scheduled reviews, take medicines as directed and report any new or rapidly worsening symptoms.</p></section>
    <section><h2>When to Seek Urgent Care</h2><p>Seek prompt medical attention for severe pain, breathing difficulty, fainting, persistent vomiting, high fever, confusion, bleeding or sudden deterioration. Emergency symptoms should not be managed through online advice alone.</p></section>
    <section><h2>Conclusion</h2><p>Awareness of {article.focus} supports earlier diagnosis and better health decisions. If symptoms persist, consult an appropriate specialist rather than relying on self-diagnosis.</p></section>
    <section className="article-faq"><h2>FAQs</h2><details><summary>Can these symptoms improve without treatment?</summary><p>Some mild symptoms may settle, but repeated or worsening symptoms need assessment to identify and address the cause.</p></details><details><summary>Which specialist should I consult?</summary><p>The right specialist depends on the main symptom. The MASSH care team can guide you to the appropriate department.</p></details><details><summary>Are diagnostic tests always required?</summary><p>Not always. Your doctor will recommend tests only when they help confirm a diagnosis or guide treatment.</p></details></section>
    <section><h2>Medical Disclaimer</h2><p>This content is for general education and does not replace consultation, diagnosis or treatment from a qualified healthcare professional.</p></section></div></article>
    <section className="article-similar"><div className="shell"><h2>Similar Blogs</h2><div className="article-similar-grid">{similar.map(item=><article key={item.slug}><img src={item.photo} alt=""/><div><h3><Link href={`/blogs/${item.slug}`}>{item.title}</Link></h3><p>{item.excerpt}</p><small>▦ {item.date}</small></div></article>)}</div></div></section><section className="article-enquiry shell"><h2>Get an Instant Callback</h2><p>Speak with a MASSH specialist for personalised guidance.</p><button data-quick-enquiry>Request a Call Back</button></section></main><SiteFooter/></div>;
}
