import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import CardSlider from "@/components/CardSlider";

const image=(id:string,w=900)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
const criticalConditions=["Acute kidney injury","Acute liver failure","Acute respiratory failure and ARDS","Acute coronary syndrome","Cardiogenic shock","COVID-19 care","Cerebral oedema","Congenital metabolic disorders","Drug overdose","Gastrointestinal emergencies","Heart failure","Influenza","Intracranial haemorrhage","Metabolic disorders","Multiple organ failure","Obstetric emergencies","Pneumonia","Pulmonary embolism","Sepsis","Septic shock","Stroke","Advanced diagnostics and imaging"];
const doctors=[["Dr. Sukhpreet Singh","Senior Consultant – Internal Medicine & Critical Care","photo-1612349317150-e413f6a5b16d"],["Dr. P. K. Bansal","Director & Senior Consultant – Internal Medicine","photo-1582750433449-648ed127bb54"],["Dr. Surya Kant Pankaj","Senior Consultant – Internal Medicine","photo-1537368910025-700350fe46c7"],["Dr. Pragyag Garg","Senior Consultant – Internal Medicine","photo-1622253692010-333f2da6031d"]];
const blogs=[["H3N2 Influenza A: Symptoms, Treatment & Expert Care","photo-1584634731339-252c581abfc5","head-to-toe-health"],["Migraines vs Headaches: Understanding the Difference","photo-1559757175-0eb30cd8c063","stomach-pain-warning"],["Asthma vs Allergies: How to Tell the Difference","photo-1579684385127-1ef15d508118","head-to-toe-health"],["How First Aid Is Given: Don't Suffer in Silence","photo-1603398938378-e54eab446dde","head-to-toe-health"]];

export default function InternalMedicinePage(){return <div className="massh-site speciality-detail-page"><SiteHeader/><main>
  <div className="shell speciality-category-breadcrumb"><Link href="/">Home</Link> › Centres of Excellence › Internal Medicine & Critical Care</div>
  <section className="speciality-category-hero internal-medicine-hero shell"><div><p>Centre of Excellence</p><h1>Leading Internal Medicine & Critical Care Specialists in Delhi</h1></div><b aria-hidden="true">▥</b></section>
  <div className="speciality-subnav"><div className="shell">Doctors</div></div>
  <div className="shell speciality-layout speciality-category-layout"><article className="speciality-article">
    <section><h2>Internal Medicine and Critical Care</h2><p>MASSH Hospital offers expert Critical Care and Internal Medicine services, specialising in the management of life-threatening conditions, chronic disease and medical emergencies. Our experienced physicians provide timely, compassionate care for conditions including respiratory failure, heart failure, stroke, sepsis and complex infections.</p><p>With advanced diagnostics, real-time monitoring and evidence-based treatment, our teams support patients through diagnosis, stabilisation, treatment and recovery.</p></section>
    <section><h2>Critical Care Medicine</h2><p>Critical care medicine, also known as intensive care medicine, deals with the management of critically ill patients who require specialised and immediate medical attention. These patients may have severe trauma, respiratory failure, multiple organ failure or other complex conditions.</p><h3>Core elements of Internal Medicine encompass at MASSH</h3><ul className="critical-condition-list">{criticalConditions.map(item=><li key={item}>{item}</li>)}</ul></section>
    <section><h2>Significance in Healthcare</h2><p>Critical Care and Internal Medicine are indispensable because they address unpredictable emergencies and medically complex disease. Physicians in this field interpret extensive clinical information, laboratory results, imaging and real-time vital signs to make timely decisions.</p><p>The speciality continues to evolve through advances in intensive-care monitoring, non-invasive respiratory support, telemedicine, precision diagnostics and personalised treatment protocols.</p></section>
    <section><h2>Advanced Critical Care Support</h2><div className="speciality-icon-grid">{[["♡","Continuous Monitoring"],["▥","Advanced Ventilation"],["✚","Emergency Response"],["◉","Multidisciplinary Care"]].map(([icon,title])=><article key={title}><b>{icon}</b><h3>{title}</h3><p>Coordinated clinical support designed for complex and high-risk conditions.</p></article>)}</div></section>
    <section><h2>When Should You Seek Critical Care?</h2><ul><li>Severe difficulty breathing or sudden chest pain</li><li>Loss of consciousness, confusion or seizures</li><li>Signs of stroke, shock or major infection</li><li>Persistent low oxygen levels or unstable vital signs</li><li>Multiple organ complications or rapid deterioration</li></ul><p>Emergency symptoms require immediate medical attention. Call emergency services or visit the nearest hospital without delay.</p></section>
  </article><aside className="speciality-sidebar"><div className="speciality-enquiry"><h2>Quick Enquiry</h2><p>Get a free call from our health advisor.</p><button data-quick-enquiry>Enquire Now</button><a href="tel:+917290975999">☎ +91-72909-75999</a></div><nav><h3>Centres of Excellence</h3>{["Advanced Urology","Kidney Stones","Enlarged Prostate (BPH)","Urinary Cancer","Laparoscopy & GI Surgery","Orthopaedics, Spine & Sports Injury","Oncology","Internal Medicine & Critical Care","Laparoscopic Gynaecology","Bariatric & Metabolic Surgery"].map(item=><span key={item}>{item}<b>›</b></span>)}</nav></aside></div>
  <section className="speciality-doctors section"><div className="shell"><div className="section-heading"><h2>Meet Our Doctors</h2><p>Exceptional medical care guided by experienced internal medicine and critical-care specialists.</p></div><CardSlider label="internal medicine doctors" className="card-grid">{doctors.map(([name,speciality,photo])=><article className="doctor-card" key={name}><img src={image(photo,500)} alt={name}/><h3>{name}</h3><p>{speciality}</p><button data-quick-enquiry>Book Appointment</button></article>)}</CardSlider></div></section>
  <section className="section speciality-hospitals"><div className="shell"><div className="section-heading"><h2>Hospitals</h2><p>Access advanced internal medicine and critical-care services across the MASSH network.</p></div><CardSlider label="MASSH hospitals" className="card-grid">{[["South Delhi","photo-1586773860418-d37222d8fce3"],["Noida","photo-1538108149393-fbbd81895907"],["Ludhiana","photo-1519494026892-80bbd2d6fd0d"],["Punjabi Bagh","photo-1516841273335-e39b37888115"]].map(([name,photo])=><article className="hospital-card" key={name}><img src={image(photo)} alt=""/><h3>{name}</h3><a href="tel:+917290975999">Call Now</a></article>)}</CardSlider></div></section>
  <section className="section internal-health-blogs"><div className="shell"><div className="section-heading"><h2>Health Blogs</h2></div><CardSlider label="internal medicine health blogs" className="card-grid">{blogs.map(([title,photo,slug])=><article className="blog-card" key={title}><img src={image(photo,600)} alt=""/><h3>{title}</h3><p>Read practical health information from MASSH specialists.</p><Link className="blog-read-link" href={`/blogs/${slug}`}>Read More</Link></article>)}</CardSlider><div className="explore"><Link className="explore-blogs-link" href="/blogs">● Explore More</Link></div></div></section>
  </main><SiteFooter/></div>}
