import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import CardSlider from "@/components/CardSlider";
import SpecialityEnquiryForm from "@/components/SpecialityEnquiryForm";

const image=(id:string,w=900)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
const doctors=[["Dr. Sachin Parikh","Minimal Access Surgery & Medical Director","photo-1612349317150-e413f6a5b16d"],["Dr. Harpreet Singh Jolly","GI, Laparoscopic & Bariatric Surgery","photo-1582750433449-648ed127bb54"],["Dr. Sushant Verma","Laparoscopy, General & Bariatric Surgery","photo-1537368910025-700350fe46c7"],["Dr. Amit Kumar","Laparoscopic GI & General Surgery","photo-1622253692010-333f2da6031d"]];
const conditions=[
  ["Appendicitis","Inflammation of the appendix requiring timely assessment.","/blogs/appendix-pain-location"],
  ["Gallstones","Stones in the gallbladder that may cause pain or inflammation.","/specialities/laparoscopic-general-surgery/gallstones"],
  ["Anal Fistula","An abnormal connection near the anal canal requiring specialist care","#"],
  ["Haemorrhoids","Swollen veins causing discomfort, bleeding or irritation.","#"],
  ["Fissure","A small tear that can cause pain and bleeding.","#"],
  ["Hernia","A weakness allowing tissue to push through the abdominal wall.","#"],
];
const faqs=["What is laparoscopic surgery?","What types of surgeries can be performed using laparoscopy?","What are the advantages of laparoscopic surgery?","What should I expect during recovery from laparoscopic surgery?","How can I prepare for laparoscopic surgery?","Who is an ideal candidate for laparoscopic surgery?","When can I resume normal activities after surgery?"];

export default function LaparoscopicSurgeryPage(){return <div className="massh-site speciality-detail-page"><SiteHeader/><main>
  <div className="shell speciality-category-breadcrumb"><Link href="/">Home</Link> › Centres of Excellence › Laparoscopy & GI Surgery</div>
  <section className="speciality-category-hero shell"><div><p>Centre of Excellence</p><h1>Leading 3D Laparoscopic Surgery Hospital in Delhi</h1></div><b aria-hidden="true">⚕</b></section>
  <div className="shell speciality-layout speciality-category-layout"><article className="speciality-article">
    <section className="speciality-opening"><div><h2>About Laparoscopic & General Surgery</h2><p>At MASSH Hospital, we provide laparoscopic general surgery using advanced minimally invasive techniques. Small incisions and a high-definition camera allow surgeons to perform precise procedures with reduced tissue disruption.</p><p>Laparoscopic surgery is also known as minimal access surgery or keyhole surgery. Compared with conventional open surgery, it generally offers less postoperative discomfort, smaller scars and faster return to everyday activities.</p></div><img src={image("photo-1551076805-e1869033e561")} alt="Laparoscopic surgical team"/></section>
    <section><h2>What is Laparoscopic Surgery?</h2><p>Laparoscopy is a surgical technique in which small incisions are created in the abdomen. A thin camera called a laparoscope displays a magnified view of the operative area on a monitor while specialised instruments are used to complete treatment.</p><ul><li><b>Smaller incisions:</b> Usually only a few small cuts are required.</li><li><b>Minimal scarring:</b> Smaller incisions generally mean smaller scars.</li><li><b>Reduced pain:</b> Less tissue disruption can reduce postoperative discomfort.</li><li><b>Faster recovery:</b> Many patients return to routine activity sooner.</li></ul><h3>The Laparoscopic Surgical Process: What to Expect</h3><div className="speciality-steps">{["Pre-surgery consultation and investigation","Anaesthesia and small-incision access","High-definition camera-guided procedure","Recovery monitoring and discharge plan"].map((step,index)=><div key={step}><b>{index+1}</b><span>{step}</span></div>)}</div></section>
    <section><h2>Advanced 3D Laparoscopic Technology: Enhancing Precision</h2><p>MASSH uses modern 3D laparoscopic visualisation that gives surgeons enhanced depth perception and a detailed view of anatomical structures.</p><ul><li>Improved visualisation of tissue planes and anatomy</li><li>Enhanced precision during complex dissection and suturing</li><li>Better surgical control with minimal access instruments</li><li>Potentially reduced risk of avoidable tissue trauma</li></ul></section>
    <section><h2>Why Choose MASSH Hospital for Laparoscopic General Surgery?</h2><ul><li><b>Experienced surgeons:</b> Specialists trained in advanced minimal access procedures.</li><li><b>Modern operation theatres:</b> High-definition equipment and strict safety protocols.</li><li><b>Patient-centred care:</b> Individual evaluation, counselling and recovery planning.</li><li><b>Comprehensive services:</b> Imaging, anaesthesia, critical care and rehabilitation support.</li><li><b>Minimal pain and faster recovery:</b> Techniques designed to support early mobility.</li></ul></section>
    <section><h2>What to Expect After Laparoscopic Surgery</h2><p>Most patients are encouraged to walk early and gradually resume food. The exact hospital stay and return-to-work timeline depend on the procedure and individual health.</p><p>Your care team provides instructions about wound care, medicines, activity, diet and follow-up appointments. Contact the hospital if you develop fever, worsening pain, persistent vomiting or wound concerns.</p></section>
    <section><h2>Laparoscopy & GI Surgery Conditions</h2><div className="condition-grid">{conditions.map(([title,desc,href])=><Link href={href} key={title}><h3>{title}</h3><p>{desc}</p><span>Learn More →</span></Link>)}</div></section>
  </article><aside className="speciality-sidebar"><SpecialityEnquiryForm source="Laparoscopic Surgery Speciality Quick Enquiry"/><nav><h3>Centres of Excellence</h3>{["Advanced Urology","Kidney Stones","Enlarged Prostate","Urinary Cancer","Laparoscopy & GI Surgery","Orthopaedics, Spine & Sports Injury","Oncology","Internal Medicine & Critical Care","Laparoscopic Gynaecology","Bariatric & Metabolic Surgery"].map(item=><span key={item}>{item}<b>›</b></span>)}</nav></aside></div>
  <section className="speciality-doctors section"><div className="shell"><div className="section-heading"><h2>Meet Our Doctors</h2><p>Consult specialists experienced in advanced laparoscopic and general surgery.</p></div><CardSlider label="laparoscopic surgeons" className="card-grid">{doctors.map(([name,speciality,photo])=><article className="doctor-card" key={name}><img src={image(photo,500)} alt={name}/><h3>{name}</h3><p>{speciality}</p><button data-quick-enquiry>Book Appointment</button></article>)}</CardSlider></div></section>
  <section className="section speciality-videos"><div className="shell"><div className="section-heading"><h2>Recommended Videos</h2></div><CardSlider label="laparoscopic surgery videos" className="video-grid">{["Laparoscopic Surgery at MASSH","Advanced 3D Laparoscopy","Patient Recovery Journey","Meet Our Surgery Team"].map((title,index)=><article className="youtube-video-card" key={title}><div className="youtube-frame"><iframe src={`https://www.youtube.com/embed/jvlwR1jTW4A?start=${index*10}`} title={title} loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div><h3>{title}</h3></article>)}</CardSlider></div></section>
  <section className="section speciality-hospitals"><div className="shell"><div className="section-heading"><h2>Hospitals</h2><p>Access minimally invasive surgical care across the MASSH hospital network.</p></div><CardSlider label="MASSH hospitals" className="card-grid">{[["South Delhi","photo-1586773860418-d37222d8fce3"],["Noida","photo-1538108149393-fbbd81895907"],["Ludhiana","photo-1519494026892-80bbd2d6fd0d"],["Punjabi Bagh","photo-1516841273335-e39b37888115"]].map(([name,photo])=><article className="hospital-card" key={name}><img src={image(photo)} alt=""/><h3>{name}</h3><a href="tel:+917290975999">Call Now</a></article>)}</CardSlider></div></section>
  <section className="speciality-faq shell"><div className="section-heading"><h2>Frequently Asked Questions</h2></div>{faqs.map(question=><details key={question}><summary>{question}</summary><p>Your surgeon will explain recommendations specific to your procedure, diagnosis and overall health.</p></details>)}</section>
  <section className="section"><div className="shell"><div className="section-heading"><h2>Health Blogs</h2></div><div className="related-service-grid"><Link href="/blogs/appendix-pain-location"><b>✚</b><span>Appendix Pain: Symptoms & When to See a Doctor</span><i>→</i></Link><Link href="/blogs/stomach-pain-warning"><b>●</b><span>Signs Your Stomach Pain Could Be Serious</span><i>→</i></Link><Link href="/blogs/learn-about-the-crucial-gallbladder-stone-symptoms-in-women"><b>◉</b><span>Gallbladder Stone Symptoms in Women</span><i>→</i></Link></div></div></section>
  </main><SiteFooter/></div>}
