import CardSlider from "@/components/CardSlider";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

const image = (id: string, width = 1000) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const leaders = [
  { name:"Riju Jhunjhunwala", role:"Promoter & Director", photo:image("photo-1560250097-0b93528c311a",600), quote:"At MASSH, our mission goes beyond medical expertise — it is about touching lives with compassion and empathy. As a patron, I am driven by the profound impact we have on our patients’ lives and honoured to be part of their healing journey." },
  { name:"Mansi Bansal Jhunjhunwala", role:"Founder and CEO", photo:image("photo-1573496359142-b8d87734a5a2",600), quote:"My goal was to create a healthcare institution that goes beyond treating illnesses. We empower individuals to prioritise their health and well-being while helping them understand the importance of restoring confidence." },
  { name:"Hanish Bansal", role:"Executive Director", photo:image("photo-1564564321837-a57b7070ac4f",600), quote:"My passion lies in making a positive impact on the lives of our patients. Together with our team and 25+ years of experience, we deliver world-class care through a patient-centric approach and cutting-edge technology." },
];
const hospitals = [
  ["South Delhi",image("photo-1586773860418-d37222d8fce3",700)], ["Noida",image("photo-1538108149393-fbbd81895907",700)],
  ["Ludhiana",image("photo-1519494026892-80bbd2d6fd0d",700)], ["Punjabi Bagh",image("photo-1576091160399-112ba8d25d1d",700)],
];

export default function MasshAbout(){return <div className="massh-site about-page"><SiteHeader/><main>
  <section className="about-hero"><div className="shell about-hero-layout"><div><h1>About Us</h1><p>Minimal Access Smart Surgery Hospital</p></div><div className="team-photo"><img src={image("photo-1584982751601-97dcc096659c",1000)} alt="MASSH medical team"/></div></div></section>
  <section className="about-intro shell"><div className="about-copy"><p>Minimal Access Smart Surgery Hospitals is a growing chain of premier Super Speciality Hospitals in India, combining the latest in cutting-edge technology with the most ethical and transformational practices to deliver world-class patient care.</p><p>Our approach to healthcare is centred around a patient-centric philosophy that focuses on enhancing health and wellness, not just treating illness. We are committed to a P5 medicine approach that focuses on Personalised, Participatory, Predictive, Preventive and Precision healthcare.</p><p>By offering groundbreaking 3D Laparoscopy, Laser and Minimal Access Surgeries, we provide our patients with safer and more effective treatments than conventional methods. Our team of full-time, dedicated senior doctors ensure continuity of care and trusted expertise across every speciality.</p></div><div className="values-grid"><article><h2>Vision</h2><p>To be a trusted partner in healthcare for our patients across India, offering top-quality care and innovative solutions that combine cutting-edge technology with compassionate treatment.</p></article><article><h2>Mission</h2><p>We go beyond just being a hospital. Our mission is to provide world-class care to every patient with cutting-edge technology, skilled doctors and a comfortable environment.</p></article><article><h2>Quality Policy</h2><p>We strive for excellence through continuous improvement and evidence-based practices. Quality outcomes and a superior experience are our priorities.</p></article></div></section>
  <section className="people-section"><div className="shell"><h2>People Behind MASSH</h2><p className="people-intro">At MASSH, our team of dedicated healthcare professionals is the driving force behind our success. Led by highly skilled doctors, surgeons and specialists, our team is committed to delivering exceptional patient care.</p><div className="leader-list">{leaders.map((leader,index)=><article className={`leader-card ${index%2?"leader-card--reverse":""}`} key={leader.name}><img src={leader.photo} alt={leader.name}/><div className="leader-quote"><span>“</span><p>{leader.quote}</p><h3>{leader.name}</h3><small>{leader.role}</small></div></article>)}</div></div></section>
  <section className="about-hospitals section"><div className="shell"><div className="section-heading"><h2>Hospitals</h2><p>MASSH Group of Hospitals is a trusted name in delivering advanced healthcare solutions with a network of premier super speciality hospitals.</p></div><CardSlider label="about page hospitals" className="about-hospital-track">{hospitals.map(([name,src])=><article className="about-hospital-card" key={name}><img src={src} alt=""/><h3>{name}</h3></article>)}</CardSlider></div></section>
  <section className="contact-section"><div className="shell"><h2>Contact Information</h2><p>To learn more about our services or to book an appointment, please contact us at:</p><div className="contact-panel"><div className="contact-details"><div><b>☎</b><p><strong>Phone Number</strong><span>011-35021666</span></p></div><div><b>◎</b><p><strong>Website</strong><span>www.massh.in</span></p></div><div><b>✉</b><p><strong>Email</strong><span>info@massh.in</span></p></div></div><img src={image("photo-1631248055158-edec7a3c072b",800)} alt="Premium hospital room"/><img src={image("photo-1631815588090-d4bfec5b1ccb",800)} alt="Modern patient room"/></div></div></section>
  </main><SiteFooter/></div>}
