import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import CardSlider from "@/components/CardSlider";
import SpecialityEnquiryForm from "@/components/SpecialityEnquiryForm";

const image=(id:string,w=900)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
const conditions=[["Knee Pain","Pain caused by injury, arthritis or joint degeneration."],["Arthritis","Progressive inflammation affecting joints and mobility."],["Sports Injuries","Sprains, ligament injuries and overuse conditions."],["Hip Pain","Discomfort affecting walking and daily activity."],["Back Pain","Muscle, disc or spine-related pain and stiffness."],["Sciatica","Pain travelling along the sciatic nerve into the leg."],["Disc Tear","Damage to the outer layer of a spinal disc."],["Frozen Shoulder","Painful stiffness restricting shoulder movement."]];
const doctors=[["Dr. Sushant Seth","Orthopaedics, Joint, Spine & Sports Injury","photo-1612349317150-e413f6a5b16d"],["Dr. Rahul Kumar","Orthopaedics, Trauma, Spine & Sports Injury","photo-1582750433449-648ed127bb54"],["Dr. Manish Goyal","Orthopaedics, Joint Replacement & Sports","photo-1537368910025-700350fe46c7"],["Dr. Sumit Paria","Orthopaedics, Spine & Sports Injury","photo-1622253692010-333f2da6031d"]];
const faqs=["What is orthopaedics?","What conditions do orthopaedic surgeons treat?","What are common symptoms of a spine injury?","How are spine injuries diagnosed?","What treatments are available for spine injuries?","What are common sports injuries?","What is arthroscopy and when is it used?","What symptoms might indicate a need for knee replacement?","What is knee replacement surgery?","What is the recovery process after knee replacement surgery?","What is joint replacement surgery?","When should I see an orthopaedic specialist?"];

export default function OrthopaedicsPage(){return <div className="massh-site speciality-detail-page"><SiteHeader/><main>
  <div className="shell speciality-category-breadcrumb"><Link href="/">Home</Link> › Centres of Excellence › Orthopaedics, Spine & Sports Injury</div>
  <section className="speciality-category-hero orthopaedics-hero shell"><div><p>Centre of Excellence</p><h1>Leading Orthopaedics & Spine Surgery Hospital in Delhi</h1></div><b aria-hidden="true">♿</b></section>
  <div className="shell speciality-layout speciality-category-layout"><article className="speciality-article">
    <section className="speciality-opening"><div><h2>Comprehensive Orthopaedic, Spine & Sports Injury Care</h2><p>At MASSH, we understand how musculoskeletal health affects every aspect of daily life. Our Orthopaedics, Spine and Sports Injury department provides comprehensive care for conditions affecting bones, joints, muscles, ligaments, tendons, nerves and the spine.</p><p>Experienced orthopaedic surgeons combine clinical assessment, modern imaging, physiotherapy and advanced surgical techniques to help relieve pain and restore movement.</p></div><img src={image("photo-1552674605-db6ffd4facb5")} alt="Sports injury and orthopaedic care"/></section>
    <section><h2>Advanced Joint and Bone Care</h2><p>Our team treats fractures, arthritis, joint degeneration, ligament injuries and complex trauma. Treatment begins with conservative options whenever appropriate and progresses to minimally invasive or reconstructive surgery when needed.</p><ul><li>Joint-preserving and cartilage procedures</li><li>Arthroscopy for knee, shoulder and sports injuries</li><li>Primary and revision joint replacement</li><li>Fracture fixation and trauma management</li><li>Rehabilitation and movement restoration</li></ul></section>
    <section><h2>Specialised Spine Services</h2><p>Spine-related conditions can significantly affect comfort, mobility and independence. MASSH specialists evaluate back pain, sciatica, disc disease, spinal stenosis and injuries using clinical examination and modern imaging.</p><ul><li>Non-surgical pain and rehabilitation plans</li><li>Image-guided and minimally invasive treatments</li><li>Microscopic and minimally invasive spine surgery</li><li>Care for slipped disc, stenosis and spinal instability</li></ul></section>
    <section><h2>Sports Injury Management</h2><p>Athletes and active individuals receive personalised care focused on safe recovery and prevention of repeat injury. Services include ligament assessment, tendon treatment, arthroscopy, strength rehabilitation and return-to-sport planning.</p><div className="speciality-steps">{["Clinical and movement assessment","Imaging and injury diagnosis","Individual treatment plan","Rehabilitation and safe return to activity"].map((step,index)=><div key={step}><b>{index+1}</b><span>{step}</span></div>)}</div></section>
    <section><h2>Orthopaedic Conditions</h2><div className="condition-grid orthopaedic-condition-grid">{conditions.map(([title,desc])=><article key={title}><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
  </article><aside className="speciality-sidebar"><SpecialityEnquiryForm source="Orthopaedics Speciality Quick Enquiry"/><nav><h3>Centres of Excellence</h3>{["Advanced Urology","Laparoscopy & GI Surgery","Orthopaedics, Spine & Sports Injury","Knee Pain","Joint Replacement","Sports Injury","Spine Surgery","Oncology","Internal Medicine & Critical Care","Laparoscopic Gynaecology","Bariatric & Metabolic Surgery"].map(item=><span key={item}>{item}<b>›</b></span>)}</nav></aside></div>
  <section className="speciality-doctors section"><div className="shell"><div className="section-heading"><h2>Meet Our Doctors</h2><p>Consult specialists in orthopaedics, joint replacement, spine surgery, trauma and sports medicine.</p></div><CardSlider label="orthopaedic doctors" className="card-grid">{doctors.map(([name,speciality,photo])=><article className="doctor-card" key={name}><img src={image(photo,500)} alt={name}/><h3>{name}</h3><p>{speciality}</p><button data-quick-enquiry>Book Appointment</button></article>)}</CardSlider></div></section>
  <section className="section speciality-videos"><div className="shell"><div className="section-heading"><h2>Recommended Videos</h2></div><CardSlider label="orthopaedic videos" className="video-grid">{["Advanced Orthopaedic Care","Knee Replacement Recovery","Sports Injury Treatment","Meet Our Orthopaedic Team"].map((title,index)=><article className="youtube-video-card" key={title}><div className="youtube-frame"><iframe src={`https://www.youtube.com/embed/jvlwR1jTW4A?start=${index*10}`} title={title} loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div><h3>{title}</h3></article>)}</CardSlider></div></section>
  <section className="section speciality-hospitals"><div className="shell"><div className="section-heading"><h2>Hospitals</h2><p>Access advanced bone, joint and spine care across the MASSH hospital network.</p></div><CardSlider label="MASSH hospitals" className="card-grid">{[["South Delhi","photo-1586773860418-d37222d8fce3"],["Noida","photo-1538108149393-fbbd81895907"],["Ludhiana","photo-1519494026892-80bbd2d6fd0d"],["Punjabi Bagh","photo-1516841273335-e39b37888115"]].map(([name,photo])=><article className="hospital-card" key={name}><img src={image(photo)} alt=""/><h3>{name}</h3><a href="tel:+917290975999">Call Now</a></article>)}</CardSlider></div></section>
  <section className="speciality-faq shell"><div className="section-heading"><h2>Frequently Asked Questions</h2></div>{faqs.map(question=><details key={question}><summary>{question}</summary><p>An orthopaedic specialist will recommend care based on examination, imaging, activity requirements and overall health.</p></details>)}</section>
  <section className="section"><div className="shell"><div className="section-heading"><h2>Health Blogs</h2></div><div className="related-service-grid"><Link href="/blogs/head-to-toe-health"><b>♿</b><span>Trusted Orthopaedic Surgeons for Knee & Hip Replacement</span><i>→</i></Link><Link href="/blogs/stomach-pain-warning"><b>●</b><span>Groin Pain Treatment and Its Causes</span><i>→</i></Link><Link href="/blogs/medicine-or-surgery"><b>◉</b><span>Hip Replacement Surgery and Recovery</span><i>→</i></Link><Link href="/blogs/after-bariatric-surgery"><b>↕</b><span>Knee Replacement Surgery: Cost, Type & Recovery</span><i>→</i></Link></div></div></section>
  </main><SiteFooter/></div>}
