import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

const image = (id:string,w=1000) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;

type Service = { title:string; intro:string; points:string[]; photo:string };
const homeServices:Service[] = [
  {title:"Elderly Care",intro:"MASSH Elderly Care offers compassionate support and round-the-clock healthcare assistance for seniors. We ensure their safety, well-being and optimal care.",points:["Daily monitoring of vitals","Oral & IV medication management","Doctor visit at home","Blood tests at home","Medicine supply at home","Assistance for radiology tests","Hospital admission assistance","Daily supervision by senior MASSH manager","Weekly updates to family members"],photo:image("photo-1559234938-b60fff04894d")},
  {title:"Critical Care",intro:"Comprehensive critical care services with state-of-the-art technology and highly trained specialists for patients with critical medical conditions.",points:["Patients dependent on medical equipment","Post-procedure nursing care","Monitoring their health status","Administration of medications","Continuous support of ICU nurses"],photo:image("photo-1576765608622-067973a79f53")},
  {title:"Palliative Care",intro:"Compassionate and holistic support for patients facing serious illnesses, enhancing quality of life and providing emotional and spiritual support.",points:["Medical evaluations and symptom monitoring","Wound care","Rehabilitation care and physical exercise","Preparing meals to patient's tastes","Frequent talking and laughter therapy","Emotional and spiritual support","End-of-life care if required"],photo:image("photo-1576091160550-2173dba999ef")},
  {title:"Home Attendant",intro:"Personalised care and support for individuals needing assistance with daily activities in their own homes, including companionship and medication management.",points:["Personal care assistance","Feeding assistance","Personal hygiene assistance","Mobility support","Assisted living services","Regular vital sign checks","Medication reminders","Emergency management and response"],photo:image("photo-1544717305-2782549b5136")},
  {title:"Covid Care Services",intro:"Necessary medical attention and support for individuals affected by the virus, including timely diagnosis, treatment, monitoring and personalised care.",points:["Trained nurse for 24-hour assistance","Daily doctor video consultation","COVID medical kits","Blood tests at home","Medicine supply","Doctor consultation at home","IV medication","Oxygen concentrator"],photo:image("photo-1584634731339-252c581abfc5")},
];

const internationalServices:Service[] = [
  {title:"Online Consultation",intro:"Receive personalised medical advice from the comfort of your home.",points:["Convenient online consultations","Get the care you need","Dedicated medical professionals"],photo:image("photo-1576091160399-112ba8d25d1d")},
  {title:"Plan Your Trip",intro:"Let us take care of the details so you can focus on your health.",points:["Customised itineraries for your needs","Travel and stay preferences","Stress-free and enjoyable logistics"],photo:image("photo-1436491865332-7a61a109cc05")},
  {title:"Medical Visa Assistance",intro:"We understand that navigating the visa process can be daunting.",points:["Support for international patients","Help obtaining necessary medical visas","Focus on getting better while we handle paperwork"],photo:image("photo-1569154941061-e231b4725ef1")},
  {title:"Insurance Assistance",intro:"Insurance can be confusing, so we offer assistance throughout the process.",points:["Navigate the process","Ensure necessary treatment coverage","Support with financial aspects of care"],photo:image("photo-1554224155-8d04cb21cd6c")},
  {title:"Transportation Arrangements",intro:"Personalised transportation arrangements from arrival to hospital and beyond.",points:["Safe airport transfers","Comfortable hospital travel","Door-to-door support"],photo:image("photo-1515569067071-ec3b51335dd0")},
  {title:"Accommodation Options",intro:"We offer convenient accommodation options for patients and families.",points:["Partner hotels and serviced apartments","Discounted international patient rates","Comfortable and accessible stay"],photo:image("photo-1566073771259-6a8506099945")},
  {title:"Billing & Payment Options",intro:"Medical bills can be confusing and overwhelming; our team provides personalised support.",points:["Understand bills and payment options","Focus on recovery","Transparent and clear assistance"],photo:image("photo-1554224154-26032ffc0d07")},
  {title:"Follow-up Care & Rehabilitation",intro:"Recovery does not stop when you leave the hospital.",points:["Personalised follow-up plans","Safe recovery support","Hospital-to-home continuity"],photo:image("photo-1576091160408-112ba8d25d1d")},
];

function ServiceRows({items,cta=false}:{items:Service[];cta?:boolean}) { return <div className="service-rows">{items.map((item,index)=><section className={`service-row ${index%2?"is-reverse":""}`} key={item.title}><div className="service-copy"><h2>{item.title}</h2><p>{item.intro}</p><h3>{cta?"Our Services Include":""}</h3><ul>{item.points.map(point=><li key={point}>{point}</li>)}</ul>{cta&&<button data-quick-enquiry>Request a Call Back</button>}</div><img src={item.photo} alt={item.title}/></section>)}</div> }

export function HomeHealthcarePage(){ return <div className="massh-site inner-service-page"><SiteHeader/><main><section className="service-hero"><div className="shell service-hero-layout"><div><h1>Home Is Where<br/>Your Health<br/>Begins</h1><p>Experience the heartfelt care of MASSH, right at your doorstep. Embrace our comprehensive home healthcare services.</p></div><img src={image("photo-1551836022-d5d88e9218df",1200)} alt="Home healthcare support for an elderly patient"/></div></section><div className="shell"><ServiceRows items={homeServices} cta/></div></main><SiteFooter/></div> }

export function InternationalPatientsPage(){ return <div className="massh-site inner-service-page"><SiteHeader/><main><section className="service-hero"><div className="shell service-hero-layout"><div><h1>MASSH<br/>International<br/>Patient Care</h1><p>Committed to providing world-class medical services to patients from all over the world.</p></div><img src={image("photo-1576765608866-5b51046452be",1200)} alt="International patient receiving care"/></div></section><div className="shell"><ServiceRows items={internationalServices}/></div></main><SiteFooter/></div> }

const hospitalItems = [
  ["MASSH Super Speciality Hospital","B-18, Chirag Enclave, New Delhi - 110048","A leading South Delhi healthcare institution offering advanced Laparoscopy, Gynaecology, Urology, Orthopaedics, Internal Medicine and Critical Care.","photo-1586773860418-d37222d8fce3","MASSH Chirag Enclave Delhi"],
  ["MASSH-MANAS Super Speciality Hospital","A-93, Sector 34, Noida - 201307","A premier healthcare institution in Noida with comprehensive medical services, modern facilities and expert multidisciplinary care.","photo-1538108149393-fbbd81895907","MASSH MANAS Noida"],
  ["MASSH-PROLIFE Super Speciality Hospital","Village Gill, Malerkotla Road, Ludhiana, Punjab - 141116","A premier hospital delivering advanced services across Laparoscopy, Orthopaedics, Urology, Bariatric Surgery and Critical Care.","photo-1519494026892-80bbd2d6fd0d","MASSH Prolife Ludhiana"],
  ["MGS-MASSH Super Speciality Hospital","35/37 Rohtak Road, West Punjabi Bagh, New Delhi - 110026","A comprehensive 150-bed healthcare institution specialising in surgical and medical services with modern technology.","photo-1516841273335-e39b37888115","MGS MASSH Punjabi Bagh"],
  ["MASSH Super Speciality Hospital","Near Nobel Public School, Garh Road, Meerut, Uttar Pradesh 250004","A trusted centre for advanced healthcare in Meerut, providing patient-focused services and high-quality care.","photo-1626315869436-d6781ba69d6e","MASSH Hospital Meerut"],
];
export function HospitalsPage(){ return <div className="massh-site hospitals-page"><SiteHeader/><main className="shell hospitals-main"><p className="breadcrumb"><b>Hospitals</b> <span>›</span> Hospital List all India</p><div className="inner-heading"><h1>MASSH Super Speciality Hospitals</h1></div><div className="hospital-list">{hospitalItems.map(([name,address,desc,photo,query])=><article key={address}><img src={image(photo,1000)} alt={name}/><div><h2>{name}</h2><p>{address}</p><p>{desc}</p><div className="hospital-actions"><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer">Get Directions</a><a href="tel:+917290975999">Call Now</a></div></div></article>)}</div></main><SiteFooter/></div> }
