import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import CardSlider from "@/components/CardSlider";
import SpecialityEnquiryForm from "@/components/SpecialityEnquiryForm";

const image=(id:string,w=900)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
const conditions=[
  ["Kidney Stones","Hard deposits that form in the kidneys and may cause severe pain.","/blogs/early-kidney-stone-signs"],
  ["Enlarged Prostate (BPH)","A non-cancerous enlargement that affects urinary flow.","#"],
  ["Ureteric Stricture","Narrowing of the ureter that can block urine flow.","#"],
  ["Urethral Stricture","Scar-related narrowing of the urinary passage.","#"],
  ["Ureteric Stones","Stones lodged in the tube between kidney and bladder.","#"],
  ["Kidney Cysts","Fluid-filled growths requiring clinical assessment.","#"],
  ["PUJ Obstruction","A blockage where the kidney connects to the ureter.","#"],
  ["Stress Urinary Incontinence","Urine leakage during coughing, sneezing or exercise.","#"],
  ["Phimosis Treatment","Care for foreskin that cannot be retracted comfortably.","#"],
];
const doctors=[["Dr. Varun Mittal","Senior Consultant – Advanced Urology","photo-1612349317150-e413f6a5b16d"],["Dr. Dheeraj Shamsukha","HOD Urology & Uro-Oncology","photo-1582750433449-648ed127bb54"],["Dr. Poonam Gulati","Chairperson – Renal Sciences","photo-1594824476967-48c8b964273f"],["Dr. Prabhat Ranjan","HOD – Urology, Uro-Oncology & Transplant","photo-1537368910025-700350fe46c7"]];
const faqs=["What is urology?","What are common urological conditions?","What should I expect during my first appointment with a urologist?","What diagnostic tests and procedures are commonly used in urology?","What are some non-surgical treatment options for urological conditions?","What urological procedures are performed by urologists and what is the recovery process?","How do I prepare for a urological procedure and what should I expect during recovery?"];

export default function UrologyPage(){return <div className="massh-site speciality-detail-page"><SiteHeader/><main>
  <div className="shell speciality-category-breadcrumb"><Link href="/">Home</Link> › Centres of Excellence › Advanced Urology</div>
  <section className="speciality-category-hero urology-hero shell"><div><p>Centre of Excellence</p><h1>Leading Advanced Urology Hospital in Delhi</h1></div><b aria-hidden="true">♜</b></section>
  <div className="shell speciality-layout speciality-category-layout"><article className="speciality-article">
    <section className="speciality-opening"><div><h2>Comprehensive Urology & Andrology Care at MASSH</h2><p>Urology is a specialised medical field focused on diagnosis, treatment and management of conditions affecting the urinary tract, kidneys, bladder, ureters and urethra.</p><p>At MASSH, our urology specialists create a supportive environment where patients can discuss concerns openly and receive personalised care.</p></div><img src={image("photo-1559757148-5c350d0d3c56")} alt="Advanced urinary system care"/></section>
    <section><h2>Fellowing Andrological Conditions</h2><p>Andrology focuses on male reproductive and sexual health. Our specialists provide confidential evaluation and evidence-based care.</p><ul><li><b>Male infertility:</b> Evaluation and treatment for sperm disorders and reproductive challenges.</li><li><b>Erectile dysfunction:</b> Advanced therapies for achieving and maintaining erections.</li><li><b>Premature ejaculation:</b> Diagnosis and treatment adapted to individual needs.</li><li><b>Low testosterone:</b> Hormonal evaluation and appropriate replacement options.</li><li><b>Varicocele:</b> Minimally invasive correction of enlarged scrotal veins.</li><li><b>Peyronie&apos;s disease:</b> Management of penile curvature and associated discomfort.</li><li><b>Male sexual health disorders:</b> Comprehensive confidential care.</li></ul></section>
    <section><h2>Treatment Approaches</h2><ul><li><b>Non-surgical treatment:</b> Lifestyle modification, medicines, physical therapy and minimally invasive procedures.</li><li><b>Minimal access surgery:</b> Laparoscopic and robotic techniques using smaller incisions.</li><li><b>Endoscopic treatment:</b> Camera-guided procedures through natural urinary passages.</li><li><b>Laser treatment:</b> Modern laser technology for stones and prostate conditions.</li></ul></section>
    <section><h2>Why MASSH Is Your Trusted Choice for Urology & Andrology Care</h2><ul><li>Experienced urology and andrology specialists</li><li>State-of-the-art diagnostic tools and surgical equipment</li><li>Patient-centred counselling and personalised treatment plans</li><li>Multidisciplinary care for complex conditions</li><li>Modern laser, endoscopic and laparoscopic technology</li></ul></section>
    <section><h2>Take Charge of Your Health</h2><p>Seeking timely medical attention for urinary or reproductive concerns is important. Symptoms such as blood in urine, pain, recurrent infection, difficulty urinating or changes in sexual health should be assessed by a qualified specialist.</p></section>
    <section><h2>Urological Conditions</h2><div className="condition-grid urology-condition-grid">{conditions.map(([title,desc,href])=><Link href={href} key={title}><h3>{title}</h3><p>{desc}</p><span>Learn More →</span></Link>)}</div></section>
  </article><aside className="speciality-sidebar"><SpecialityEnquiryForm source="Urology Speciality Quick Enquiry"/><nav><h3>Centres of Excellence</h3>{["Advanced Urology","Kidney Stones","Enlarged Prostate (BPH)","Ureteric Stricture","Urethral Stricture","Ureteric Stones","Kidney Cysts","PUJ Obstruction","Stress Urinary Incontinence","Phimosis Treatment","Laparoscopy & GI Surgery","Orthopaedics, Spine & Sports Injury","Oncology","Internal Medicine & Critical Care"].map(item=><span key={item}>{item}<b>›</b></span>)}</nav></aside></div>
  <section className="speciality-doctors section"><div className="shell"><div className="section-heading"><h2>Meet Our Doctors</h2><p>Consult experienced specialists in urology, andrology, kidney stones and minimally invasive treatment.</p></div><CardSlider label="urology doctors" className="card-grid">{doctors.map(([name,speciality,photo])=><article className="doctor-card" key={name}><img src={image(photo,500)} alt={name}/><h3>{name}</h3><p>{speciality}</p><button data-quick-enquiry>Book Appointment</button></article>)}</CardSlider></div></section>
  <section className="section speciality-videos"><div className="shell"><div className="section-heading"><h2>Recommended Videos</h2></div><CardSlider label="urology videos" className="video-grid">{["Advanced Urology at MASSH","Laser Treatment for Kidney Stones","Understanding Prostate Care","Meet Our Urology Team"].map((title,index)=><article className="youtube-video-card" key={title}><div className="youtube-frame"><iframe src={`https://www.youtube.com/embed/jvlwR1jTW4A?start=${index*10}`} title={title} loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div><h3>{title}</h3></article>)}</CardSlider></div></section>
  <section className="section speciality-hospitals"><div className="shell"><div className="section-heading"><h2>Hospitals</h2><p>Advanced urological care is available across the MASSH hospital network.</p></div><CardSlider label="MASSH hospitals" className="card-grid">{[["South Delhi","photo-1586773860418-d37222d8fce3"],["Noida","photo-1538108149393-fbbd81895907"],["Ludhiana","photo-1519494026892-80bbd2d6fd0d"],["Punjabi Bagh","photo-1516841273335-e39b37888115"]].map(([name,photo])=><article className="hospital-card" key={name}><img src={image(photo)} alt=""/><h3>{name}</h3><a href="tel:+917290975999">Call Now</a></article>)}</CardSlider></div></section>
  <section className="speciality-faq shell"><div className="section-heading"><h2>Frequently Asked Questions</h2></div>{faqs.map(question=><details key={question}><summary>{question}</summary><p>Your urologist will recommend evaluation and treatment based on symptoms, diagnosis and overall health.</p></details>)}</section>
  <section className="section"><div className="shell"><div className="section-heading"><h2>Health Blogs</h2></div><div className="related-service-grid"><Link href="/blogs/early-kidney-stone-signs"><b>◉</b><span>10 Early Signs of Kidney Stones You Should Never Ignore</span><i>→</i></Link><Link href="/blogs/head-to-toe-health"><b>✚</b><span>Kidney Stone Specialists Near You</span><i>→</i></Link><Link href="/blogs/stomach-pain-warning"><b>●</b><span>Laser Treatment for Kidney Stones</span><i>→</i></Link><Link href="/blogs/fatty-liver-symptoms"><b>▥</b><span>Kidney Stone Specialist Near You in Punjabi Bagh</span><i>→</i></Link></div></div></section>
  </main><SiteFooter/></div>}
